cc_library(
    name = "tensorflowlib",
    srcs = ["lib/libtensorflow.so","lib/libtensorflow_framework.so","lib/libtensorflow.so.2","lib/libtensorflow_framework.so.2","lib/libtensorflow.so.2.4.0","lib/libtensorflow_framework.so.2.4.0"],
    hdrs = ["include/tensorflow/c/eager/c_api.h","include/tensorflow/c/c_api.h", "include/tensorflow/c/c_api_experimental.h", "include/tensorflow/c/tensor_interface.h","include/tensorflow/c/tf_attrtype.h", "include/tensorflow/c/tf_datatype.h", "include/tensorflow/c/tf_file_statistics.h", "include/tensorflow/c/tf_status.h", "include/tensorflow/c/tf_tensor.h", "include/tensorflow/c/tf_tstring.h", "include/tensorflow/core/platform/ctstring.h", "include/tensorflow/core/platform/ctstring_internal.h"],
    visibility = ["//visibility:public"],
)


cc_library(
  name="tensorflow_include",
  hdrs=["include/tensorflow/c/eager/c_api.h","include/tensorflow/c/c_api.h", "include/tensorflow/c/c_api_experimental.h", "include/tensorflow/c/tensor_interface.h","include/tensorflow/c/tf_attrtype.h", "include/tensorflow/c/tf_datatype.h", "include/tensorflow/c/tf_file_statistics.h", "include/tensorflow/c/tf_status.h", "include/tensorflow/c/tf_tensor.h", "include/tensorflow/c/tf_tstring.h", "include/tensorflow/core/platform/ctstring.h", "include/tensorflow/core/platform/ctstring_internal.h"],
)